### ISSUE TITLE
Não consigo configurar ajustes de posicionamento no Block para os devices mobile

### ISSUE THREAD

**Issue by gbombassaro** [xproglabs/xprog-designsystem#17]
Podemos configurar para o componente diversas entradas para os breakpoints. Cada entrada vai corresponder a um token no design-system e podemos configurar essas chamadas para receberem um array. Para o usuário final, um array com todas as configurações de layout referentes àquele breakpoint que ele deseja, isso será recebido por uma props - nome do breakpoint.

Nome do arquivo: Block.js

**Comment by bombassaro** [comment]
Resolvido com as props xs, sm, md, lg e xl
