### ISSUE TITLE
Não consigo manipular os espaçamentos que estão linkados ao Block.js

### ISSUE THREAD

**Issue by gbombassaro** [xproglabs/xprog-designsystem#19]
Podemos criar uma forma de o Block.js entender os tokens de espaçamento que serão cadastrados no design-system para evitar que o componente fique engessado. Pode ser um switch que compreenda os tokens e aplique o espaçamento correspondente a ele.

**Comment by bombassaro** [comment]
Feito considerando o space-unit / size para as props m, p, h, w, suas variações
